import {defaultScene,validateProject,renderProject,renderScene,sceneAt} from './engine/render.js';
import {preloadProject,qualityCheck} from './engine/pro.js';
const $=id=>document.getElementById(id),studio=()=>window.canvasStudio,p=()=>studio().project,s=()=>p().scenes[studio().selected];let objectId='',pending=null,versionTimer,jobTimer;const mathState={expression:'a*x^2',other:'x*x',from:-3,to:3,parameter:1,yFrom:-10,yTo:10,tex:'\\int_0^1 x^2\\,dx=\\frac{1}{3}',resultTex:''};
const button=document.createElement('button');button.id='professionalOpen';button.className='text-button';button.textContent='Stüdyo araçları';document.querySelector('.atelier-nav').prepend(button);
const work=document.createElement('section');work.id='professionalTools';work.hidden=true;work.className='pro-workbench';work.setAttribute('aria-label','Profesyonel stüdyo araçları');
work.innerHTML=`<header><div><span class="pro-eyebrow">Çalışma masası</span><h2>Fikrinin ayrıntılarını işle.</h2></div><button id="proClose" aria-label="Araçları kapat">×</button></header><nav id="proTabs" aria-label="Stüdyo araçları"></nav><div class="pro-body"><aside class="pro-preview"><span id="proSceneName"></span><canvas id="proStage" width="1280" height="720" aria-label="Seçili sahne önizlemesi"></canvas><label>Önizleme zamanı<input id="proSeek" type="range" min="0" step=".01"></label><p>Katman modunda nesneleri burada sürükleyebilirsin.</p></aside><div id="proContent"></div></div><p id="proStatus" role="status" aria-live="polite"></p><progress id="proProgress" max="100" value="0" hidden></progress><div id="proResult"></div>`;document.querySelector('.workspace').after(work);
const tabs={style:'Stil & nesneler',board:'Senaryo',layers:'Katman & hareket',math:'Matematik',voice:'Ses masası',patch:'AI düzeltme',quality:'Kontrol & kaynak',versions:'Sürüm & teslim'};let tab='style';
for(const [id,label] of Object.entries(tabs)){const b=document.createElement('button');b.dataset.tool=id;b.textContent=label;b.onclick=()=>{tab=id;refresh();};$('proTabs').append(b);}
const message=text=>$('proStatus').textContent=text;
async function api(name,body,raw=false){const r=await fetch('/api/animation/'+name,{method:'POST',headers:raw?{}:{'Content-Type':'application/json'},body:raw?body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error||'İşlem tamamlanamadı');return value;}
const edit=fn=>{const ok=studio().edit(fn);if(ok)refresh();else message($('notice').textContent);return ok;},selected=()=>s().objects.find(o=>o.id===objectId),content=()=>$('proContent');
function field(label,type,value,id){const l=document.createElement('label');l.textContent=label;const input=document.createElement(type==='textarea'?'textarea':type==='select'?'select':'input');input.id=id;if(type!=='textarea'&&type!=='select')input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value??'';l.append(input);return l;}
function selectField(label,id,options,value){const l=field(label,'select','',id);for(const [v,t] of options){const o=document.createElement('option');o.value=v;o.textContent=t;l.lastChild.append(o);}l.lastChild.value=value;return l;}
function action(label,fn,primary=false){const b=document.createElement('button');b.textContent=label;if(primary)b.className='coral';b.onclick=async()=>{try{await fn();}catch(e){message(e.message);}};return b;}
function grid(){const div=document.createElement('div');div.className='pro-grid';content().append(div);return div;}
const choices=['solid','watercolor','pastel','ink','retro'].map(v=>[v,{solid:'Düz çizim',watercolor:'Suluboya',pastel:'Pastel',ink:'Mürekkep',retro:'Retro'}[v]]);
function stylePanel(){const q=p(),g=grid();g.append(field('Stili bütün sahnelere kilitle','checkbox',q.style.locked,'masterLock'),selectField('Yazı dili','masterFont',[['Manrope','Manrope'],['Kalam','Kalam']],q.style.font),selectField('Fırça davranışı','masterBrush',choices,q.style.brush),selectField('Ortak hareket dili','masterMotion',[['draw','Çizilerek'],['fade','Belirerek'],['float','Salınarak'],['rotate','Dönerek'],['slide','Kayarak']],q.style.motion),field('Ana çizgi kalınlığı','number',q.style.lineWidth,'masterWidth'),field('Arka plan','color',q.style.background,'masterBg'),field('Palet · virgülle ayrılmış HEX','text',q.style.palette.join(', '),'masterPalette'));
  content().append(action('Proje stilini uygula',()=>edit(pr=>{pr.style={locked:$('masterLock').checked,font:$('masterFont').value,brush:$('masterBrush').value,motion:$('masterMotion').value,lineWidth:Number($('masterWidth').value),background:$('masterBg').value,palette:$('masterPalette').value.split(',').map(v=>v.trim())};}),true));
  const h=document.createElement('h3');h.textContent='Ortak nesne kütüphanesi';content().append(h);const note=document.createElement('p');note.className='muted';note.textContent='Sahnenin düzenlenebilir çizimini kaydet; kopyaları aynı nesneye bağlı kalsın. Prosedürel örneği önce katman araçlarıyla nesnelere dönüştür.';content().append(note,field('Nesne adı','text','Yeni ortak nesne','assetName'),action('Sahne nesnelerini kütüphaneye kaydet',()=>{if(!s().objects.length)throw Error('Sahnede kaydedilecek düzenlenebilir nesne yok');edit(pr=>pr.assets.push({id:crypto.randomUUID(),name:$('assetName').value,revision:1,objects:structuredClone(s().objects).map(o=>({...o,assetId:'',entityId:'',locked:false}))}));}));
  for(const a of q.assets){const row=document.createElement('div');row.className='pro-row';const name=document.createElement('span');name.textContent=`${a.name} · sürüm ${a.revision}`;row.append(name,action('Sahneye bağla',()=>edit(pr=>{const o=newObject('rect');o.assetId=a.id;o.entityId=a.id;o.name=a.name;o.width=.7;o.height=.7;pr.scenes[studio().selected].objects.push(o);pr.scenes[studio().selected].composed=true;})),action('Bu çizimle ortak nesneyi güncelle',()=>{if(s().objects.some(o=>o.assetId))throw Error('Ortak nesneyi yalnızca bağımsız nesnelerden güncelle');edit(pr=>{const target=pr.assets.find(x=>x.id===a.id);target.objects=structuredClone(s().objects);target.revision++;});}));content().append(row);}
}
function newObject(type){return {id:crypto.randomUUID(),name:type,type,x:.5,y:.4,width:.2,height:.15,color:p().style.palette[0],lineWidth:3,start:0,duration:2,motion:'draw',text:type==='text'?'Yeni etiket':'',points:type==='path'?[[.2,.4],[.4,.2],[.6,.5],[.8,.3]]:[],opacity:1,scale:1,rotation:0,brush:p().style.brush};}
function boardPanel(){const note=document.createElement('p');note.textContent='Anlatımı, görsel yönü ve sıralamayı üretimden önce Doküman & uzun animasyon alanında incele. Burada açık filmin sahnelerini düzenle.';content().append(note,action('Dokümandan senaryo hazırla',()=>{$('productionOpen').click();}));for(const [i,scene] of p().scenes.entries()){if(Math.abs(i-studio().selected)>7)continue;const row=document.createElement('article');row.className='pro-board-row';const cv=document.createElement('canvas');cv.width=240;cv.height=135;renderScene(cv.getContext('2d'),scene.duration*.7,scene,p());const wrap=document.createElement('div'),h=document.createElement('h3');h.textContent=`${i+1}. ${scene.title}`;const label=field('Görsel yön / devamlılık notu','textarea',scene.notes,'notes'+i);label.lastChild.onchange=e=>edit(pr=>{pr.scenes[i].notes=e.target.value;});const narr=field('Anlatım','textarea',scene.narration,'narr'+i);narr.lastChild.onchange=e=>edit(pr=>{pr.scenes[i].narration=e.target.value;delete pr.scenes[i].audio;pr.scenes[i].words=[];});const duration=field('Süre (2–120 sn)','number',scene.duration,'boardDuration'+i);duration.lastChild.onchange=e=>edit(pr=>pr.scenes[i].duration=Number(e.target.value));wrap.append(h,duration,label,narr,action('Sahneye git',()=>{studio().select(i);refresh();}),action('Öne taşı',()=>edit(pr=>{if(i>0)[pr.scenes[i-1],pr.scenes[i]]=[pr.scenes[i],pr.scenes[i-1]];})));row.append(cv,wrap);content().append(row);}}
function layersPanel(){const scene=s(),row=document.createElement('div');row.className='pro-row';for(const [type,label] of [['circle','Daire'],['rect','Dikdörtgen'],['path','Fırça yolu'],['text','Metin']])row.append(action('＋ '+label,()=>edit(pr=>{const o=newObject(type);objectId=o.id;pr.scenes[studio().selected].objects.push(o);pr.scenes[studio().selected].composed=true;})));content().append(row);const l=field('Önceki sahnenin nesne durumunu devam ettir','checkbox',scene.carry,'carryScene');l.lastChild.onchange=e=>edit(pr=>pr.scenes[studio().selected].carry=e.target.checked);content().append(l);
  const g=grid(),list=document.createElement('div');list.className='pro-layer-list';g.append(list);for(const o of [...scene.objects].reverse()){const b=action(`${o.locked?'🔒 ':''}${o.hidden?'○ ':'● '}${o.name}`,()=>{objectId=o.id;refresh();});b.classList.toggle('active',o.id===objectId);list.append(b);}g.classList.add('pro-layer-grid');const panel=document.createElement('div');panel.className='pro-properties';g.append(panel);const o=selected();if(!o){panel.textContent='Bir nesne seç. Önizlemede sürükleyebilir, alttan hareket anahtarları ekleyebilirsin.';return;}
  for(const [key,label,type] of [['name','Ad','text'],['x','x (0–1)','number'],['y','y (0–1)','number'],['width','Genişlik (0–1)','number'],['height','Yükseklik (0–1)','number'],['rotation','Dönüş (derece)','number'],['scale','Ölçek (0,01–10)','number'],['start','Başlama zamanı (sn)','number'],['duration','Belirme / çizim süresi (sn)','number'],['opacity','Saydamlık (0–1)','number'],['color','Renk','color'],['text','Etiket','text'],['entityId','Devamlılık kimliği','text'],['group','Grup kimliği','text'],['locked','Kilitle','checkbox'],['hidden','Gizle','checkbox']]){const l=field(label,type,o[key],`obj_${key}`);if(type==='number')l.lastChild.step='.01';l.lastChild.disabled=o.locked&&key!=='locked';l.lastChild.onchange=e=>{const value=type==='checkbox'?e.target.checked:type==='number'?Number(e.target.value):e.target.value;edit(pr=>{const target=pr.scenes[studio().selected].objects.find(x=>x.id===objectId);if(['x','y'].includes(key)){const delta=value-target[key];for(const item of pr.scenes[studio().selected].objects.filter(x=>!x.locked&&(x.id===objectId||target.group&&x.group===target.group))){item[key]+=delta;if(item.type==='path')item.points=item.points.map(pt=>pt.map((v,i)=>i===(key==='x'?0:1)?v+delta:v));}}else target[key]=value;});};panel.append(l);}
  const motion=selectField('Hareket türü','objectMotion',[['draw','Çizilerek'],['fade','Belirerek'],['float','Salınarak'],['rotate','Dönerek'],['slide','Kayarak']],o.motion);motion.lastChild.disabled=o.locked;motion.lastChild.onchange=e=>edit(pr=>pr.scenes[studio().selected].objects.find(x=>x.id===objectId).motion=e.target.value);panel.append(motion);
  const brush=selectField('Fırça','objectBrush',choices,o.brush);brush.lastChild.disabled=o.locked;brush.lastChild.onchange=e=>edit(pr=>pr.scenes[studio().selected].objects.find(x=>x.id===objectId).brush=e.target.value);panel.append(brush);
  panel.append(action('Bir katman öne',()=>edit(pr=>{const a=pr.scenes[studio().selected].objects,i=a.findIndex(x=>x.id===objectId);if(i<a.length-1)[a[i],a[i+1]]=[a[i+1],a[i]];})),action('Seçili nesneyi sil',()=>{if(o.locked)throw Error('Nesne kilitli');edit(pr=>pr.scenes[studio().selected].objects=pr.scenes[studio().selected].objects.filter(x=>x.id!==objectId));}));
  const h=document.createElement('h3');h.textContent='Hareket anahtarları';panel.append(h,field('Sahne içi zaman (sn)','number',sceneAt(p(),studio().time).local,'keyTime'),selectField('Hareket eğrisi','keyEase',[['smooth','Yumuşak'],['linear','Doğrusal'],['hold','Bekle']], 'smooth'),action('Bu konumu anahtar kare yap',()=>{if(o.locked)throw Error('Nesne kilitli');edit(pr=>{const target=pr.scenes[studio().selected].objects.find(x=>x.id===objectId);const frame={time:Number($('keyTime').value),ease:$('keyEase').value,...Object.fromEntries(['x','y','rotation','opacity','scale'].map(k=>[k,target[k]]))};target.keyframes=target.keyframes.filter(k=>k.time!==frame.time);target.keyframes.push(frame);});}));
  for(const k of o.keyframes||[])panel.append(action(`${k.time} sn · ${k.ease} · kaldır`,()=>{if(!o.locked)edit(pr=>{const target=pr.scenes[studio().selected].objects.find(x=>x.id===objectId);target.keyframes=target.keyframes.filter(x=>x.time!==k.time);});}));
  if(scene.words?.length){panel.append(selectField('Konuşma işareti','cueWord',scene.words.map((w,i)=>[String(i),`${i+1}. ${w.w} · ${w.start} sn`]),String(o.cue?.word||0)),action('Hareketi seçili kelimeye bağla',()=>{if(!o.locked)edit(pr=>pr.scenes[studio().selected].objects.find(x=>x.id===objectId).cue={word:Number($('cueWord').value),offset:0});}));}else panel.append(action('Önce sesi kelimelere hizala',()=>job('align',{project:p()})));
}
async function typeset(tex){if(!window.MathJax?.tex2svgPromise){window.MathJax={svg:{fontCache:'local'}};await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='../node_modules/mathjax-full/es5/tex-svg.js';script.onload=resolve;script.onerror=reject;document.head.append(script);});await MathJax.startup.promise;}return MathJax.tex2svgPromise(tex,{display:true}).then(el=>{const svg=el.querySelector('svg');svg.style.color=p().style.palette[0];return svg.outerHTML;});}
function mathPanel(){const g=grid();g.append(field('İfade · x, a, sin(x), x^2…','text',mathState.expression,'mathExpr'),field('Karşılaştırılacak ifade','text',mathState.other,'mathOther'),field('Aralık başlangıcı','number',mathState.from,'mathFrom'),field('Aralık sonu','number',mathState.to,'mathTo'),field('a parametresi','range',mathState.parameter,'mathParam'),field('y ekseni alt sınırı','number',mathState.yFrom,'mathYFrom'),field('y ekseni üst sınırı','number',mathState.yTo,'mathYTo'));$('mathParam').min=-5;$('mathParam').max=5;$('mathParam').step=.1;const result=document.createElement('div');result.id='mathResult';content().append(result);
  async function calculate(actionName){Object.assign(mathState,{expression:$('mathExpr').value,other:$('mathOther').value,from:Number($('mathFrom').value),to:Number($('mathTo').value),parameter:Number($('mathParam').value),yFrom:Number($('mathYFrom').value),yTo:Number($('mathYTo').value)});if(!Number.isFinite(mathState.yFrom+mathState.yTo)||mathState.yFrom>=mathState.yTo)throw Error('y ekseni sınırlarını kontrol et');const data=await api('pro/math',{expression:$('mathExpr').value,other:$('mathOther').value,from:Number($('mathFrom').value),to:Number($('mathTo').value),parameter:Number($('mathParam').value),action:actionName});mathState.resultTex=data.latex;result.textContent=data.equivalent!==undefined?`${data.equivalent?'Eşdeğer':'Eşdeğer değil'} · ${data.domainNote}`:data.result||data.expression;return data;}
  content().append(action('Eşdeğerliği kontrol et',()=>calculate('equivalence')),action('Türev',()=>calculate('derivative')),action('Belirli integral',()=>calculate('integral')),Object.assign(action('Grafiği sahneye çiz',async()=>{const data=await calculate('plot'),valid=data.points.filter(Boolean),min=mathState.yFrom,max=mathState.yTo,span=max-min||1,segments=[];let points=[];for(const q of data.points){if(q&&q[1]>=min&&q[1]<=max)points.push([.15+.7*(q[0]-Number($('mathFrom').value))/(Number($('mathTo').value)-Number($('mathFrom').value)),.78-.66*(q[1]-min)/span]);else if(points.length){segments.push(points);points=[];}}if(points.length)segments.push(points);edit(pr=>{const scene=pr.scenes[studio().selected];scene.objects=scene.objects.filter(o=>!o.math?.plot);for(const pts of segments.filter(v=>v.length>1)){const o=newObject('path');o.points=pts;o.name=data.expression;o.math={expression:mathState.expression,plot:true,parameter:mathState.parameter,from:mathState.from,to:mathState.to,yFrom:min,yTo:max};scene.objects.push(o);}const axes=[];if(min<=0&&max>=0){const y=.78-.66*(0-min)/span;axes.push([[.15,y],[.85,y]]);}if(mathState.from<=0&&mathState.to>=0){const x=.15+.7*(0-mathState.from)/(mathState.to-mathState.from);axes.push([[x,.12],[x,.78]]);}for(const pts of axes){const axis=newObject('path');axis.points=pts;axis.color='#94888f';axis.lineWidth=1;axis.name='Grafik ekseni';axis.math={expression:'0',plot:true,axis:true,parameter:mathState.parameter};axis.motion='draw';scene.objects.unshift(axis);}const label=newObject('text');label.text=`f(x)=${mathState.expression} · a=${mathState.parameter} · x:[${mathState.from},${mathState.to}] y:[${min},${max}]`;label.name='Grafik aralığı';label.y=.075;label.width=.8;label.height=.025;label.math={expression:mathState.expression,plot:true,label:true,parameter:mathState.parameter};scene.objects.push(label);scene.composed=true;});}),{id:'mathGraph'}),field('TeX formülü','text',mathState.tex,'mathTex'),action('Formülü sahneye ekle',async()=>{mathState.tex=$('mathTex').value;const svg=await typeset(mathState.tex);edit(pr=>{const o=newObject('text');o.svg=svg;o.width=.65;o.height=.18;o.name='TeX formülü';o.text='';pr.scenes[studio().selected].objects.push(o);pr.scenes[studio().selected].composed=true;});},true));
  content().append(action('Son matematik sonucunu anlatım adımı olarak ekle',async()=>{if(!mathState.resultTex)throw Error('Önce türev veya integral hesapla');const svg=await typeset(mathState.resultTex);edit(pr=>{const scene=pr.scenes[studio().selected],o=newObject('text');o.svg=svg;o.name='Hesaplama adımı';o.text='';o.width=.6;o.height=.15;o.y=.3;o.start=Math.min(scene.duration-.2,sceneAt(p(),studio().time).local);o.motion='fade';scene.objects.push(o);scene.composed=true;});}));
  $('mathParam').onchange=()=>{if(s().objects.some(o=>o.math?.plot))$('mathGraph').click();else message(`a = ${$('mathParam').value}`);};
}
function voicePanel(){const q=p(),g=grid();g.append(selectField('Sabit anlatıcı','voiceProvider',[['windows','Yerel Türkçe · Tolga'],['cartesia','Cartesia · ayarlıysa']],q.voice.provider),field('Konuşma hızı (0,5–2)','number',q.voice.rate,'voiceRate'),field('Cümle duraklaması (ms)','number',q.voice.pause,'voicePause'),field('Perde (−10…10 yarım ses)','number',q.voice.pitch,'voicePitch'),field('Telaffuz sözlüğü · JSON','textarea',JSON.stringify(q.voice.lexicon,null,2),'voiceLexicon'));
  content().append(action('Anlatıcı ayarlarını kaydet',()=>edit(pr=>pr.voice={provider:$('voiceProvider').value,rate:Number($('voiceRate').value),pause:Number($('voicePause').value),pitch:Number($('voicePitch').value),lexicon:JSON.parse($('voiceLexicon').value)})),action('Projeyi seslendir',()=>job('voice',{project:p(),provider:p().voice.provider}),true),action('Konuşmayı kelimelere hizala',()=>job('align',{project:p()})));
  const music=field('Müzik / atmosfer WAV, MP3 · kısa dosya döngüye alınır','file','','musicFile');music.lastChild.accept='.wav,.mp3,.ogg,.m4a';music.lastChild.onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const voice=await api('audio?name='+encodeURIComponent(f.name),f,true);edit(pr=>pr.music={...voice,volume:.2,duck:.25});}catch(error){message(error.message);}};content().append(music,field('Müzik düzeyi (0–1)','number',q.music?.volume??.2,'musicVolume'),field('Konuşurken müzik çarpanı (0–1)','number',q.music?.duck??.25,'musicDuck'),action('Müzik ayarlarını uygula',()=>edit(pr=>{if(pr.music){pr.music.volume=Number($('musicVolume').value);pr.music.duck=Number($('musicDuck').value);}})),action('Müziği kaldır',()=>edit(pr=>pr.music=null)));const note=document.createElement('p');note.className='muted';note.textContent='Yerel ses hız, duraklama ve perde kullanır. Cartesia sesi hesap ayarını kullanır. Altyazı eşleşme sayısı ve eksik kelimeler sahnede görünür.';content().append(note);for(const scene of q.scenes)if(scene.alignment){const text=document.createElement('p');text.textContent=`${scene.title}: ${scene.alignment}`;content().append(text);}}
function patchPanel(){content().append(selectField('Düzeltme kapsamı','patchScope',[['object','Seçili nesne'],['scene','Sahne çizimi'],['background','Arka plan rengi'],['interval','Başlama zamanı bu aralıkta olan nesneler']],objectId?'object':'scene'),field('Aralık başlangıcı (sn)','number',0,'patchFrom'),field('Aralık sonu (sn)','number',s().duration,'patchTo'),selectField('Düzeltilecek alan','patchObject',[['','Sahne · kilitli nesneleri koru'],...s().objects.map(o=>[o.id,o.name+(o.locked?' · kilitli':'')])],objectId),field('Ne değişsin?','textarea','','patchPrompt'),action('Düzeltme taslağı hazırla',()=>job('patch',{project:p(),sceneIndex:studio().selected,scope:$('patchScope').value,from:Number($('patchFrom').value),to:Number($('patchTo').value),objectId:$('patchObject').value,prompt:$('patchPrompt').value}),true));const note=document.createElement('p');note.textContent='Taslak karşılaştırıldıktan sonra uygulanır. Önceki proje sürümü ve geri al korunur.';content().append(note);}
function qualityPanel(){const issues=qualityCheck(p());const h=document.createElement('h3');h.textContent=issues.length?`${issues.filter(i=>i.kind==='error').length} hata · ${issues.filter(i=>i.kind==='warning').length} uyarı`:'Yapısal kontrollerde sorun bulunmadı';content().append(h);for(const issue of issues){const i=p().scenes.findIndex(s=>s.id===issue.scene);content().append(action(`${i+1}. sahne · ${issue.kind==='error'?'Hata':'Uyarı'} · ${issue.message}`,()=>{studio().select(i);objectId=issue.object;tab='layers';refresh();}));}const note=document.createElement('p');note.textContent='Kontroller içerik doğruluğunu garanti etmez. Anlatımı kaynakla karşılaştır; matematik eşitliklerini Matematik aracında kontrol et.';content().append(note);content().append(action('Sunucuda kaynak ve medya kontrolünü çalıştır',async()=>{const value=await api('pro/quality',{project:p()});message(value.issues.length?value.issues.map(i=>i.message).join(' · '):'Kaynak ve medya kontrolünde sorun bulunmadı.');}));if(p().source)content().append(action('Kaynak dokümanı yan yana incele',async()=>{const r=await fetch(`/api/animation/assets/${p().source.id}/document.json`);if(!r.ok)throw Error('Kaynak doküman bulunamadı');const doc=await r.json(),g=grid(),a=document.createElement('pre'),b=document.createElement('pre');a.textContent=doc.text;b.textContent=p().scenes.map(s=>`${s.title}\n${s.sourceRefs.join(', ')}\n${s.narration}`).join('\n\n');g.append(a,b);}));}
function versionsPanel(){content().append(selectField('Video teslim boyutu','delivery',[['720','720p · 1280×720'],['1080','1080p · 1920×1080'],['4k','4K · 3840×2160'],['vertical','Dikey · 1080×1920']],p().delivery),field('Şeffaf arka plan · PNG/HTML için','checkbox',p().transparent,'transparent'),action('Teslim ayarlarını uygula',()=>edit(pr=>{pr.delivery=$('delivery').value;pr.transparent=$('transparent').checked;})),action('Projeyi medya dosyalarıyla paketle',async()=>link(await api('pro/package',{project:p()}),'zip','Proje paketini indir')),field('Proje paketi (.zip)','file','','packageFile'),action('SRT / VTT altyazıları hazırla',async()=>{const value=await api('pro/captions',{project:p()});link(value,'srt','SRT indir');link(value,'vtt','VTT indir');}),action('Sürüm kaydet',async()=>{await api('pro/revision',{project:p()});message('Sürüm diske kaydedildi.');loadVersions();}),action('MP4 renderını aç',()=>window.kareRender.open(),true));$('packageFile').accept='.zip';$('packageFile').onchange=async e=>{try{const result=await api('package-import',e.target.files[0],true);studio().import(result.project);refresh();message('Medya ve proje içe aktarıldı.');}catch(error){message(error.message);}};const div=document.createElement('div');div.id='versionList';content().append(div);loadVersions();}
function link(value,kind,label){const a=document.createElement('a');a.href=value[kind]||value.url;a.download=kind==='zip'?'kare-project.zip':'captions.'+kind;a.textContent=label;a.className='outline-button';$('proResult').append(a);}
async function loadVersions(){try{const projectId=p().id,value=await api('pro/versions',{id:projectId});if(projectId!==p().id)return;$('versionList')?.replaceChildren();for(const v of value.versions)$('versionList')?.append(action(`${new Date(v.createdAt*1000).toLocaleString('tr')} · ${v.name} · geri yükle`,async()=>{const result=await api('pro/restore',{id:projectId,revision:v.revision});studio().import(result.project);refresh();}));}catch(error){message(error.message);}}
function refresh(){if(work.hidden)return;renderProject($('proStage').getContext('2d'),studio().time,p());$('proSceneName').textContent=s().title;$('proSeek').max=s().duration;$('proSeek').value=sceneAt(p(),studio().time).local;$('proContent').replaceChildren();for(const b of $('proTabs').children)b.setAttribute('aria-pressed',String(b.dataset.tool===tab));({style:stylePanel,board:boardPanel,layers:layersPanel,math:mathPanel,voice:voicePanel,patch:patchPanel,quality:qualityPanel,versions:versionsPanel})[tab]();}
button.onclick=()=>{work.hidden=!work.hidden;if(!work.hidden){studio().pause();refresh();work.scrollIntoView({block:'start',behavior:'smooth'});}};$('proClose').onclick=()=>work.hidden=true;
async function job(type,body){clearTimeout(jobTimer);$('proResult').replaceChildren();message('İş sıraya alınıyor…');const result=await api('jobs',{type,...body});localStorage.setItem('kare-pro-job',result.id);poll(result.id);}
async function poll(id){try{const r=await fetch('/api/animation/jobs/'+id),j=await r.json();if(!r.ok)throw Error(j.error);$('proProgress').hidden=false;$('proProgress').value=j.progress;message(j.message);if(['queued','running'].includes(j.state)){if(!$('proCancel')){const cancel=action('Üretimi iptal et',()=>api('cancel/'+id,{}));cancel.id='proCancel';$('proResult').append(cancel);}jobTimer=setTimeout(()=>poll(id),2000);return;}$('proCancel')?.remove();if(j.state==='done'&&j.result.project){pending=j.result.project;await preloadProject(pending);$('proResult').replaceChildren();if(j.type==='patch'){const compare=document.createElement('div');compare.className='pro-grid';for(const [label,project] of [['Önce',j.result.originalProject||p()],['Taslak',pending]]){const figure=document.createElement('figure'),cv=document.createElement('canvas'),caption=document.createElement('figcaption');caption.textContent=label;cv.width=640;cv.height=360;renderScene(cv.getContext('2d'),project.scenes[j.result.sceneIndex||0].duration*.7,project.scenes[j.result.sceneIndex||0],project);figure.append(cv,caption);compare.append(figure);}$('proResult').append(compare);} $('proResult').append(action('Sonucu projeye uygula',async()=>{await api('pro/revision',{project:p()});if(j.result.patch&&['object','background'].includes(j.result.patch.scope)){const patch=j.result.patch,next=pending.scenes.find(s=>s.id===patch.sceneId);const ok=edit(pr=>{const scene=pr.scenes.find(s=>s.id===patch.sceneId);if(!scene)throw Error('Taslağın sahnesi silinmiş');if(patch.scope==='background')scene.background=next.background;else{const i=scene.objects.findIndex(o=>o.id===patch.objectId);if(i<0||scene.objects[i].locked)throw Error('Nesne silinmiş veya kilitlenmiş');scene.objects[i]=structuredClone(next.objects.find(o=>o.id===patch.objectId));}});if(ok){pending=null;$('proResult').replaceChildren();message('Seçili bölge güncellendi; diğer düzenlemeler ve önceki sürüm korundu.');}return;}const index=studio().selected;studio().import(pending);studio().select(Math.min(index,p().scenes.length-1));pending=null;refresh();message('Uygulandı; geri al ile önceki projeye dönebilirsin.');}),action('Taslağı kapat',()=>{$('proResult').replaceChildren();pending=null;}));}}catch(error){message(error.message);}}
addEventListener('kare-project-change',()=>{clearTimeout(versionTimer);versionTimer=setTimeout(()=>api('pro/revision',{project:p()}).catch(error=>message('Otomatik sürüm kaydı: '+error.message)),4000);});
addEventListener('kare-selection-change',()=>{if(!document.activeElement?.closest('#professionalTools'))refresh();});
$('proSeek').oninput=e=>{studio().seek(p().scenes.slice(0,studio().selected).reduce((n,s)=>n+s.duration,0)+Number(e.target.value));refresh();};
for(const stage of [$('stage'),$('proStage')]){let drag=null;stage.addEventListener('pointerdown',e=>{if(work.hidden||tab!=='layers')return;const rect=stage.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width,y=(e.clientY-rect.top)/rect.height,o=[...s().objects].reverse().find(o=>!o.hidden&&!o.locked&&Math.abs(o.x-x)<Math.max(o.width/2,.025)&&Math.abs(o.y-y)<Math.max(o.height/2,.025));if(!o)return;studio().pause();objectId=o.id;drag={x,y,project:p()};stage.setPointerCapture(e.pointerId);refresh();});
stage.addEventListener('pointermove',e=>{if(!drag)return;const r=stage.getBoundingClientRect(),dx=(e.clientX-r.left)/r.width-drag.x,dy=(e.clientY-r.top)/r.height-drag.y,q=structuredClone(drag.project),o=q.scenes[studio().selected].objects.find(x=>x.id===objectId);o.x+=dx;o.y+=dy;if(o.type==='path')o.points=o.points.map(([x,y])=>[x+dx,y+dy]);try{validateProject(q);renderProject(stage.getContext('2d'),studio().time,q);drag.next=q;}catch{}});
stage.addEventListener('pointerup',()=>{if(drag?.next){const next=drag.next;edit(pr=>pr.scenes=next.scenes);}drag=null;});stage.addEventListener('pointercancel',()=>drag=null);}
try{const id=localStorage.getItem('kare-pro-job');if(id)poll(id);}catch{}

if(new URLSearchParams(location.search).has("tools"))button.click();
