/* One MP4 workflow shared by the Canvas editor and the original lesson engine. */
import {qualityCheck} from './engine/pro.js';
const $=id=>document.getElementById(id),math=!!$('fr'),key=math?'math-render-job':'canvas-render-job';
let active=null,timer=null,working=false,resultId=null;
const terminal=new Set(['done','error','cancelled']);
const dialog=document.createElement('dialog');dialog.id='renderDialog';dialog.className='render-dialog';dialog.setAttribute('aria-labelledby','renderHeading');
dialog.innerHTML=`<header class="render-head"><div><span class="render-eyebrow">MP4 · H.264</span><h2 id="renderHeading">Filmini dışa aktar.</h2></div><button id="renderClose" aria-label="Render penceresini kapat">×</button></header><p id="renderSummary"></p><div class="render-specs"><span id="renderResolution"></span><span>30 kare / saniye</span><span id="renderAudioInfo"></span></div><label id="renderScopeLabel" ${math?'':'hidden'}>İçerik<select id="renderScope"><option value="lesson">Dersin tamamı</option><option value="scene">Seçili sahne</option></select></label><label class="render-check"><input id="renderSubtitles" type="checkbox"> Anlatım altyazısını ekle</label><p class="render-note" id="renderNote"></p><div class="render-progress-area"><progress id="renderProgress" value="0" max="100"></progress><p id="renderStatus" role="status" aria-live="polite">Hazır olduğunda renderı başlat.</p></div><div id="renderResult"></div><footer class="render-actions"><button id="renderCancel" hidden>Renderı iptal et</button><button id="renderStart" class="render-primary">MP4 renderı başlat ↗</button></footer><p class="render-note">Render sunucuda sürer. Bu pencereyi kapatabilir, stüdyoda çalışmaya devam edebilirsin.</p><details class="render-history"><summary>Önceki MP4 dosyaları</summary><div id="renderHistory"></div></details>`;
document.body.append(dialog);
async function api(path,body){const response=await fetch('/api/animation/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok){const error=new Error(value.error||'Render bağlantısı kurulamadı');error.status=response.status;throw error;}return value;}
function remember(id){try{localStorage.setItem(key,id);}catch{}}
function busy(value){working=value;$('renderStart').disabled=value;$('renderCancel').hidden=!value;$('renderScope').disabled=value;$('renderSubtitles').disabled=value;}
function label(seconds){return seconds<60?`${seconds.toFixed(1)} saniye`:`${(seconds/60).toFixed(1)} dakika`;}
function snapshot(){
  if(math){const w=$('fr').contentWindow;if(!w?.__ready)throw new Error('Ders tahtasının yüklenmesini bekle.');const selected=w.__segs.find(s=>s.id===seg()),all=$('renderScope').value==='lesson';return {type:'math-render',scope:all?'lesson':'scene',segment:seg(),title:all?'Çift integraller · Fubini':ST.script[seg()].summary,duration:all?w.__total:selected.end-selected.start,count:all?w.__segs.length:1};}
  const project=structuredClone(window.canvasStudio.project);return {type:'render',project,title:project.name,duration:project.scenes.reduce((n,s)=>n+s.duration,0),count:project.scenes.length};
}
function describe(){try{const data=snapshot();$('renderSummary').textContent=`${data.title} · ${data.count} sahne · ${label(data.duration)}`;$('renderResolution').textContent=math?'1920 × 1080':{'720':'1280 × 720','1080':'1920 × 1080','4k':'3840 × 2160',vertical:'1080 × 1920'}[data.project.delivery||'720'];if(!math){const count=data.project.scenes.filter(s=>s.audio).length;$('renderAudioInfo').textContent=count?`${count}/${data.count} sahnede ses`:'Sessiz video';$('renderNote').textContent=count?'Eklediğin sahne sesleri MP4 dosyasına dahil edilir.':'Henüz ses dosyası yok; MP4 sessiz olacak. Anlatım & ses alanından ses ekleyebilirsin.';}else{$('renderAudioInfo').textContent='Mevcut onaylı sesler';$('renderNote').textContent='Mevcut assets/narration kayıtları zamanlamalarıyla eklenir. Ses dosyası olmayan bölümler sessiz kalır.';}}catch(error){$('renderSummary').textContent=error.message;}}
function download(job){const a=document.createElement('a');a.href=job.result.url;a.download=(job.result.name||'kare-animasyon').replace(/[\/:*?"<>|]/g,'-')+'.mp4';a.className='render-primary';a.textContent='MP4 indir ↓';return a;}
async function show(job){active=job.id;remember(active);busy(!terminal.has(job.state));$('renderProgress').value=job.progress;$('renderStatus').textContent=job.state==='done'?`MP4 hazır · ${label(job.result.duration)} · ${job.result.hasAudio?'sesli':'sessiz'}`:job.message;if(job.state==='done'&&resultId!==job.id){resultId=job.id;const video=document.createElement('video');video.controls=true;video.preload='metadata';video.src=job.result.url;video.setAttribute('aria-label','Render edilen MP4 önizlemesi');const caption=document.createElement('p');caption.className='render-note';caption.textContent=`Son render: ${job.result.name||'Animasyon'} · ${new Date(job.createdAt*1000).toLocaleString('tr')}`;$('renderResult').replaceChildren(caption,video,download(job));if(job.result.audioUrl){const a=document.createElement('a');a.href=job.result.audioUrl;a.download='ses-miksi.wav';a.textContent='Ses miksini WAV indir ↓';a.className='render-primary';$('renderResult').append(a);}if(job.result.cachedScenes!==undefined){const note=document.createElement('p');note.textContent=job.result.cachedScenes+' sahne önbellekten kullanıldı.';note.className='render-note';$('renderResult').append(note);}}if(job.state==='error'||job.state==='cancelled'){$('renderStart').textContent='Yeniden render al ↗';}}
async function history(){try{const data=await api('jobs');$('renderHistory').replaceChildren();for(const job of data.jobs.filter(j=>j.type===(math?'math-render':'render')).slice(0,10)){const row=document.createElement('button');row.className='render-history-row';row.disabled=working;row.textContent=`${new Date(job.createdAt*1000).toLocaleString('tr')} · ${job.message}`;row.onclick=async()=>{if(working)return;clearTimeout(timer);resultId=null;active=job.id;remember(active);$('renderResult').replaceChildren();await poll();};$('renderHistory').append(row);}if(!$('renderHistory').children.length)$('renderHistory').textContent='Henüz MP4 üretimi yok.';}catch(error){$('renderStatus').textContent=error.message;}}
async function poll(){clearTimeout(timer);if(!active)return;try{const job=await api('jobs/'+active);await show(job);if(!terminal.has(job.state))timer=setTimeout(poll,1500);else await history();}catch(error){$('renderStatus').textContent=error.message;if(error.status===404){active=null;busy(false);try{localStorage.removeItem(key);}catch{}}else timer=setTimeout(poll,5000);}}
function open(){if(math){if(ST.rec||ST.busy){$('pmsg').textContent='Önce kaydı veya ses işlemini tamamla.';return;}stopAudio();}else window.canvasStudio.pause();describe();if(!working)$('renderSubtitles').checked=math?false:window.canvasStudio.project.subtitles;dialog.showModal();history();if(active)poll();}
$('renderOpen').onclick=open;$('renderClose').onclick=()=>dialog.close();$('renderScope').onchange=describe;
$('renderStart').onclick=async()=>{try{const data=snapshot();busy(true);resultId=null;$('renderResult').replaceChildren();$('renderProgress').value=0;$('renderStatus').textContent='Render sıraya alınıyor…';const request=math?{type:data.type,scope:data.scope,segment:data.segment}:{type:data.type,project:data.project};if(!math){const issues=qualityCheck(data.project),errors=issues.filter(i=>i.kind==='error');if(errors.length)throw Error('Render öncesi kontrol: '+errors.map(i=>i.message).join(' · '));}const job=await api('jobs',{...request,subtitles:$('renderSubtitles').checked});active=job.id;remember(active);await poll();}catch(error){busy(false);$('renderStatus').textContent=error.message;}};
$('renderCancel').onclick=async()=>{try{if(active){await api('cancel/'+active,{});await poll();}}catch(error){$('renderStatus').textContent=error.message;}};
window.kareRender={open};
if($('productionExportOpen'))$('productionExportOpen').onclick=()=>{$('exportDialog').close();open();};
if($('renderProduction'))$('renderProduction').onclick=()=>{$('productionDialog').close();open();};
try{active=localStorage.getItem(key);if(active)poll();}catch{}
