import {CATEGORIES} from './engine/catalog.js';
import {defaultScene,renderScene} from './engine/render.js';
const $=id=>document.getElementById(id);
let plan=null,documentId=null,active=null,resumeId=null,timer=null;
const terminal=new Set(['done','error','cancelled']);
async function api(path,body,raw=false){const r=await fetch('/api/animation/'+path,body===undefined?{}:{method:'POST',headers:raw?{}:{'Content-Type':'application/json'},body:raw?body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error||'İşlem tamamlanamadı');return result;}
function message(text){$('productionStatus').textContent=text;}
function busy(value){for(const id of ['createPlan','buildProduction','voiceProduction','renderProduction','saveProduction'])$(id).disabled=value||(id==='buildProduction'&&!plan);$('cancelProduction').hidden=!value;}
function remember(id){try{localStorage.setItem('canvas-production-job',id);}catch{}}
function planView(value){
  plan=structuredClone(value);$('planScenes').replaceChildren();$('planSummary').textContent=`${plan.title} · ${plan.scenes.length} sahne · ${(plan.scenes.reduce((n,s)=>n+s.duration,0)/60).toFixed(1)} dakika`;
  plan.scenes.forEach((scene,i)=>{const card=document.createElement('section');card.className='plan-scene';const h=document.createElement('h4');h.textContent=`${i+1}. ${scene.title}`;const info=document.createElement('p');info.className='muted';info.textContent=`${scene.duration} sn · ${CATEGORIES.find(c=>c.id===scene.category)?.name} · Kaynak: ${scene.sourceRefs.join(', ')||'İstekten'} `;
    const label=document.createElement('label');label.textContent='Anlatım';const narration=document.createElement('textarea');narration.rows=4;narration.maxLength=4000;narration.value=scene.narration;narration.setAttribute('aria-label',`Sahne ${i+1} anlatımı`);narration.oninput=()=>{scene.narration=narration.value;};label.append(narration);
    const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Görsel yön';const visual=document.createElement('textarea');visual.rows=3;visual.maxLength=2400;visual.value=scene.visual;visual.setAttribute('aria-label',`Sahne ${i+1} görsel yönü`);visual.oninput=()=>scene.visual=visual.value;details.append(summary,visual);const timing=document.createElement('label');timing.textContent='Süre (2–120 sn)';const duration=document.createElement('input');duration.type='number';duration.min=2;duration.max=120;duration.value=scene.duration;duration.setAttribute('aria-label',`Sahne ${i+1} süresi`);duration.onchange=()=>{scene.duration=Number(duration.value);};timing.append(duration);const category=document.createElement('select');category.setAttribute('aria-label',`Sahne ${i+1} kategorisi`);for(const c of CATEGORIES){const opt=document.createElement('option');opt.value=c.id;opt.textContent=c.name;category.append(opt);}category.value=scene.category;category.onchange=()=>{scene.category=category.value;planView(plan);};const reference=document.createElement('figure'),cv=document.createElement('canvas'),caption=document.createElement('figcaption');cv.width=240;cv.height=135;cv.style.maxWidth='240px';cv.style.width='100%';renderScene(cv.getContext('2d'),5,defaultScene(scene.category));caption.textContent='Kategori hareket referansı · nihai sahne üretimden sonra';reference.append(cv,caption);const move=document.createElement('button');move.textContent='Önceki sıraya taşı';move.disabled=i===0;move.onclick=()=>{[plan.scenes[i-1],plan.scenes[i]]=[plan.scenes[i],plan.scenes[i-1]];planView(plan);};card.append(h,info,reference,timing,category,label,details,move);$('planScenes').append(card);
  });$('buildProduction').disabled=false;
}
function applyButton(project,label='Projeyi editörde aç'){
  const button=document.createElement('button');button.className='primary';button.textContent=label;button.onclick=()=>{window.canvasStudio.import(project);$('productionDialog').close();};$('productionResult').append(button);
}
async function showJob(job){
  active=job.id;remember(job.id);$('productionProgress').value=job.progress;message(job.message);busy(!terminal.has(job.state));$('resumeProduction').hidden=true;$('productionResult').replaceChildren();
  if(job.state==='done'){
    if(job.result.plan)planView(job.result.plan);
    if(job.result.project)applyButton(job.result.project,job.type==='voice'?'Sesli projeyi editörde aç':'Çizimleri editörde aç');
    if(job.result.url){const a=document.createElement('a');a.href=job.result.url;a.download='animasyon.mp4';a.textContent=job.result.hasAudio?'Sesli MP4 indir ↗':'Sessiz MP4 indir ↗';a.className='primary';$('productionResult').append(a);const info=document.createElement('p');info.className='muted';info.textContent=`${(job.result.duration/60).toFixed(1)} dakika · ${job.result.width||1280}×${job.result.height||720} · 30 FPS`; $('productionResult').append(info);}
  }
  if((job.state==='error'||job.state==='cancelled')&&job.partialProject){applyButton(job.partialProject,'Tamamlanan sahneleri aç');if(job.type==='build'){resumeId=job.id;try{const previous=await api('assets/'+job.id+'/plan.json');planView(previous);$('resumeProduction').hidden=false;}catch{message(job.message+' · Aynı plan açıkken kaldığı yerden devam edebilirsin.');$('resumeProduction').hidden=!plan;}}}
}
async function poll(){clearTimeout(timer);if(!active)return;try{const job=await api('jobs/'+active);await showJob(job);if(!terminal.has(job.state))timer=setTimeout(poll,2000);else await history();}catch(e){message(e.message);timer=setTimeout(poll,5000);}}
async function begin(type,body){try{busy(true);$('productionResult').replaceChildren();message('Üretim sıraya alınıyor…');const job=await api('jobs',{type,...body});active=job.id;remember(active);await poll();}catch(e){busy(false);message(e.message);}}
async function history(){try{const data=await api('jobs');$('productionJobs').replaceChildren();for(const job of data.jobs.slice(0,15)){const button=document.createElement('button');button.className='job-row';button.textContent=`${{plan:'Plan',build:'Çizim',voice:'Ses',render:'Video','math-render':'Matematik videosu',align:'Hizalama',patch:'AI düzeltme'}[job.type]} · ${job.message} · ${new Date(job.createdAt*1000).toLocaleString('tr')}`;button.onclick=()=>{clearTimeout(timer);active=job.id;poll();};$('productionJobs').append(button);}}catch(e){message(e.message);}}
async function open(){window.canvasStudio.pause();$('productionDialog').showModal();try{const [cap,connection]=await Promise.all([api('production'),api('status')]);$('productionConnection').textContent=connection.configured?`${connection.provider.toUpperCase()} · ${connection.model} · Üretimler hesabının API kotasını kullanır.`:'AI bağlantısı ayarlı değil.';$('productionVoice').replaceChildren();for(const voice of cap.voices){const option=document.createElement('option');option.value=voice.id;option.textContent=voice.label+(voice.available?'':' · ayarlı değil');option.disabled=!voice.available;$('productionVoice').append(option);}const available=cap.voices.find(v=>v.available);if(available)$('productionVoice').value=available.id;await history();if(active)poll();}catch(e){message(e.message);}}
for(const category of CATEGORIES){const o=document.createElement('option');o.value=category.id;o.textContent=category.name;$('productionCategory').append(o);}$('productionCategory').value='data-viz';
$('homeProduction').onclick=$('productionOpen').onclick=open;
$('documentFile').onchange=async()=>{const f=$('documentFile').files[0];if(!f)return;documentId=null;try{if(f.size>20*1024*1024)throw new Error('Doküman en fazla 20 MB olabilir');$('documentStatus').textContent='Doküman okunuyor…';const doc=await api('document?name='+encodeURIComponent(f.name),f,true);documentId=doc.id;$('clearDocument').hidden=false;$('documentStatus').textContent=`${doc.name} · ${doc.characters.toLocaleString('tr')} karakter · ${doc.sections.length} metin bölümü${doc.warnings.length?' · '+doc.warnings.join(' '):''}`;$('documentPreviewDetails').hidden=false;$('documentPreview').textContent=doc.text.slice(0,12000)+(doc.text.length>12000?'\n… Önizlemenin ilk 12.000 karakteri; model metnin tamamını okuyacak.':'');}catch(e){$('documentStatus').textContent=e.message;}};
$('createPlan').onclick=()=>{const duration=Number($('targetMinutes').value)*60;if(!Number.isFinite(duration)||duration<30||duration>10800){message('Hedef süre 0,5–180 dakika olmalı.');return;}begin('plan',{documentId,prompt:$('productionPrompt').value,category:$('productionCategory').value,theme:$('productionTheme').value,durationSeconds:duration});};
$('buildProduction').onclick=()=>{if(plan)begin('build',{plan,projectSettings:window.canvasStudio.project});};$('resumeProduction').onclick=()=>{if(plan&&resumeId)begin('build',{plan,resumeJobId:resumeId,projectSettings:window.canvasStudio.project});};
$('voiceProduction').onclick=()=>begin('voice',{project:window.canvasStudio.project,provider:$('productionVoice').value});
$('renderProduction').onclick=()=>begin('render',{project:window.canvasStudio.project,subtitles:$('productionSubtitles').checked});
$('cancelProduction').onclick=async()=>{if(active){try{await api('cancel/'+active,{});poll();}catch(e){message(e.message);}}};
$('saveProduction').onclick=async()=>{try{const result=await api('save',{project:window.canvasStudio.project});message('Proje sunucudaki diske kaydedildi.');const link=document.createElement('a');link.href=result.url;link.download='proje.json';link.textContent='Proje dosyasını indir ↗';$('productionResult').replaceChildren(link);}catch(e){message(e.message);}};
try{active=localStorage.getItem('canvas-production-job');if(active)poll();}catch{}

$('clearDocument').onclick=()=>{documentId=null;$('documentFile').value='';$('clearDocument').hidden=true;$('documentPreviewDetails').hidden=true;$('documentStatus').textContent='Kaynak kaldırıldı; yalnızca yazdığın istek kullanılacak.';};

$('productionExportOpen').onclick=()=>{$('exportDialog').close();open();};

if(new URLSearchParams(location.search).has('production'))open();
