export const ENGINE_VERSION='kare-pro-1';
const number=(v,min,max,name)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw Error(`${name}: ${min}–${max}`);return v;};
const id=v=>String(v||'').slice(0,80);
export function objectMeta(source,index){
  const o={id:id(source.id)||`o${index}`,name:String(source.name||source.text||source.type).slice(0,100),locked:!!source.locked,hidden:!!source.hidden,carried:!!source.carried,assetId:id(source.assetId),entityId:id(source.entityId),group:id(source.group),opacity:number(source.opacity??1,0,1,'Saydamlık'),rotation:number(source.rotation??0,-3600,3600,'Dönüş'),scale:number(source.scale??1,.01,10,'Ölçek'),brush:source.brush||'solid',cue:source.cue||null,keyframes:[],svg:source.svg||'',math:source.math||null};
  if(!['solid','watercolor','pastel','ink','retro'].includes(o.brush))throw Error('Fırça geçersiz');
  if(o.svg&&(typeof o.svg!=='string'||o.svg.length>500000||!o.svg.includes('<svg')||/<script|foreignObject|on\w+\s*=|(?:href|src)\s*=\s*["'](?!#)/i.test(o.svg)))throw Error('Formül SVG geçersiz');
  if(o.math){if(typeof o.math.expression!=='string'||o.math.expression.length>160)throw Error('Matematik ifadesi geçersiz');o.math=JSON.parse(JSON.stringify(o.math));}
  if(o.cue){if(!Number.isInteger(o.cue.word))throw Error('Kelime indeksi tamsayı olmalı');o.cue={word:number(o.cue.word,0,2000,'Kelime indeksi'),offset:number(o.cue.offset||0,-10,10,'İşaret farkı')};}
  if(!Array.isArray(source.keyframes||[])||(source.keyframes||[]).length>120)throw Error('En fazla 120 anahtar kare');
  o.keyframes=(source.keyframes||[]).map(k=>{const frame={time:number(k.time,0,120,'Anahtar kare zamanı'),ease:k.ease||'smooth'};if(!['linear','smooth','hold'].includes(frame.ease))throw Error('Hareket eğrisi geçersiz');for(const field of ['x','y','opacity','rotation','scale'])if(k[field]!==undefined)frame[field]=number(k[field],field==='rotation'?-3600:0,field==='rotation'?3600:field==='scale'?10:1,field);return frame;}).sort((a,b)=>a.time-b.time);
  return o;
}
export function projectMeta(p,validateScene){
  const style=p.style||{},voice=p.voice||{},master={locked:!!style.locked,palette:(style.palette||p.scenes[0].palette).slice(0,8),background:style.background||p.scenes[0].background,font:style.font||'Manrope',brush:style.brush||'solid',motion:style.motion||'draw',lineWidth:number(style.lineWidth??3,.1,30,'Ana çizgi kalınlığı')};
  if(!['draw','fade','float','rotate','slide'].includes(master.motion))throw Error('Ana hareket geçersiz');
  if(!['Manrope','Kalam'].includes(master.font)||!['solid','watercolor','pastel','ink','retro'].includes(master.brush)||master.palette.length<2||[master.background,...master.palette].some(c=>!/^#[0-9a-f]{6}$/i.test(c)))throw Error('Proje stili geçersiz');
  if(!Array.isArray(p.assets||[])||(p.assets||[]).length>120)throw Error('En fazla 120 ortak nesne');
  const assets=(p.assets||[]).map(a=>{const objects=validateScene({...p.scenes[0],objects:a.objects}).objects;if(objects.some(o=>o.assetId))throw Error('Ortak nesneler iç içe bağlanamaz');return {id:id(a.id),name:String(a.name||'Nesne').slice(0,100),revision:number(a.revision||1,1,100000,'Nesne sürümü'),objects};});
  if(assets.some(a=>!a.id)||new Set(assets.map(a=>a.id)).size!==assets.length)throw Error('Ortak nesne kimlikleri benzersiz olmalı');
  for(const s of p.scenes){if(new Set(s.objects.map(o=>o.id)).size!==s.objects.length)throw Error('Nesne kimlikleri benzersiz olmalı');for(const o of s.objects)if(o.assetId&&!assets.some(a=>a.id===o.assetId))throw Error('Ortak nesne bulunamadı');}
  if(!['windows','cartesia'].includes(voice.provider||'windows'))throw Error('Anlatıcı geçersiz');
  const lexicon=voice.lexicon||{};if(Object.keys(lexicon).length>100||Object.entries(lexicon).some(([a,b])=>a.length>100||typeof b!=='string'||b.length>200))throw Error('Telaffuz sözlüğü geçersiz');
  const music=p.music?{...p.music,volume:number(p.music.volume??.2,0,1,'Müzik düzeyi'),duck:number(p.music.duck??.25,0,1,'Konuşmada müzik')}:null;
  if(music&&!/^\/api\/animation\/assets\/[0-9a-f-]{36}\/[\w-]+\.wav$/.test(music.url))throw Error('Müzik adresi geçersiz');
  const preset=p.delivery||'720';if(!['720','1080','4k','vertical'].includes(preset))throw Error('Çıktı boyutu geçersiz');
  return {id:/^[0-9a-f-]{36}$/.test(p.id||'')?p.id:crypto.randomUUID(),engine:ENGINE_VERSION,style:master,assets,voice:{provider:voice.provider||'windows',rate:number(voice.rate??1,.5,2,'Konuşma hızı'),pause:number(voice.pause??250,0,2000,'Cümle duraklaması'),pitch:number(voice.pitch??0,-10,10,'Ses perdesi'),lexicon},music,delivery:preset,transparent:!!p.transparent};
}
export function enforceStyle(p){if(!p.style?.locked)return p;for(const s of p.scenes){s.palette=[...p.style.palette];s.background=p.style.background;}for(const s of [...p.scenes,...p.assets]){for(const o of s.objects){if(o.locked)continue;if(!p.style.palette.includes(o.color))o.color=p.style.palette[0];o.lineWidth=p.style.lineWidth;o.brush=p.style.brush;o.motion=p.style.motion;if(o.svg)o.svg=o.svg.replace(/(<svg\b[^>]*)(>)/i,(_,tag,end)=>tag.replace(/\sstyle="[^"]*"/i,'')+' style="color:'+o.color+'"'+end);}}return p;}
export function pose(o,t,scene){
  const result={...o};if(o.cue&&scene.words?.[o.cue.word])result.start=Math.max(0,scene.words[o.cue.word].start+o.cue.offset);
  for(const property of ['x','y','rotation','opacity','scale']){const frames=o.keyframes?.filter(k=>k[property]!==undefined)||[];if(!frames.length)continue;let before={time:0,[property]:o[property]},after;for(const frame of frames){if(frame.time<=t)before=frame;else{after=frame;break;}}if(!after){result[property]=before[property];continue;}let u=Math.max(0,Math.min(1,(t-before.time)/(after.time-before.time||1)));if(after.ease==='smooth')u=u*u*(3-2*u);if(after.ease==='hold')u=0;result[property]=before[property]+(after[property]-before[property])*u;}
  return result;
}
export function carryScene(project,index){const s=project.scenes[index];if(!s.carry||!index)return s;const entities=new Map();for(let i=0;i<index;i++){if(i&&!project.scenes[i].carry)entities.clear();const previous=project.scenes[i];for(const o of previous.objects)if(o.entityId&&!o.hidden&&o.start<previous.duration){const end=pose(o,previous.duration,previous);if(o.motion==='float')end.y+=Math.sin((previous.duration-end.start)*previous.speed*1.5)*14/720;if(o.motion==='rotate')end.rotation+=(previous.duration-end.start)*previous.speed*.3*180/Math.PI;if(end.type==='path')end.points=end.points.map(([x,y])=>[Math.max(0,Math.min(1,x+end.x-o.x)),Math.max(0,Math.min(1,y+end.y-o.y))]);entities.set(o.entityId,{...end,carried:true,start:0,duration:.1,motion:'fade',cue:null,keyframes:[]});}}
  for(const o of s.objects)if(o.entityId)entities.delete(o.entityId);return {...s,objects:[...entities.values(),...s.objects]};
}
const svgImages=new Map();
export async function preloadProject(p){const svgs=[...p.scenes.flatMap(s=>s.objects),...p.assets.flatMap(a=>a.objects)].map(o=>o.svg).filter(Boolean);await Promise.all(svgs.map(svg=>{if(svgImages.has(svg))return;return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{svgImages.set(svg,img);resolve();};img.onerror=()=>reject(Error('Formül görseli yüklenemedi'));img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);});}));}
export function formulaImage(svg){return svgImages.get(svg);}
export function brushPath(ctx,points,o,seed,progress){
  let state=seed>>>0;const random=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296;};
  const end=Math.max(2,Math.ceil(points.length*progress)),p=points.slice(0,end);ctx.strokeStyle=o.color;ctx.lineCap='round';ctx.lineJoin='round';
  const passes=o.brush==='watercolor'?7:o.brush==='pastel'?10:1;
  for(let k=0;k<passes;k++){ctx.save();ctx.globalAlpha*=o.brush==='watercolor'?.12:o.brush==='pastel'?.25:1;ctx.lineWidth=o.lineWidth*(o.brush==='watercolor'?1+k*.4:o.brush==='ink'?.5+Math.sin(k+progress*5)*.4:1);ctx.beginPath();p.forEach(([x,y],i)=>{const jitter=o.brush==='pastel'?3:o.brush==='watercolor'?2:0;x+=(random()-.5)*jitter;y+=(random()-.5)*jitter;if(o.brush==='retro'){x=Math.round(x/8)*8;y=Math.round(y/8)*8;}i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.restore();}
}
export function qualityCheck(p){const issues=[],push=(s,o,kind,message)=>issues.push({scene:s.id,object:o?.id||'',kind,message});for(const s of p.scenes){if(s.narration&&!s.audio)push(s,null,'warning','Anlatımın ses dosyası yok');if(s.audio?.duration>s.duration)push(s,null,'error','Ses sahne süresini aşıyor');if(s.words?.some(w=>w.matched===false))push(s,null,'warning','Bazı kelime zamanları ASR eşleşmediği için tahmini');if(s.words?.some(w=>w.end>s.duration))push(s,null,'error','Kelime zamanları sahne süresini aşıyor');if(s.narration&&!s.words?.length)push(s,null,'warning','Kelime hizalaması yok; altyazı yaklaşık');if(s.sourceRefs.length&&!p.source)push(s,null,'warning','Kaynak referansının dokümanı projede yok');if(p.style?.locked&&(s.background!==p.style.background||JSON.stringify(s.palette)!==JSON.stringify(p.style.palette)))push(s,null,'error','Sahne proje stiliyle uyuşmuyor');for(const o of s.objects){if(o.hidden)continue;const radius=o.type==='circle'?o.width*1280/720:o.height;if(o.x-o.width/2<0||o.x+o.width/2>1||o.y-radius/2<0||o.y+radius/2>1)push(s,o,'warning','Nesne çerçevenin dışına taşıyor');if(o.type==='text'&&o.height*720<18)push(s,o,'warning','Etiket çok küçük');if(o.keyframes?.some(k=>(k.x??o.x)-o.width/2<0||(k.x??o.x)+o.width/2>1||(k.y??o.y)-radius/2<0||(k.y??o.y)+radius/2>1))push(s,o,'warning','Hareket nesneyi çerçeve dışına taşıyor');if(o.type==='text'&&!o.svg){const luminance=c=>{const v=c.match(/[a-f0-9]{2}/gi).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722;};const a=luminance(o.color),b=luminance(s.background);if((Math.max(a,b)+.05)/(Math.min(a,b)+.05)<3)push(s,o,'warning','Metin ve arka planın kontrastı düşük');}if(o.start>=s.duration)push(s,o,'error','Nesne sahne bitmeden görünmüyor');if(o.cue&&!s.words?.[o.cue.word])push(s,o,'error','Konuşma işareti için hizalanmış kelime yok');if(o.keyframes?.some(k=>k.time>s.duration))push(s,o,'warning','Anahtar kare sahne süresini aşıyor');}}return issues;}
export function subtitleFile(p,format='srt'){const lines=[];let offset=0,n=0;const stamp=t=>{const ms=Math.round(t*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}${format==='vtt'?'.':','}${String(ms%1000).padStart(3,'0')}`;};for(const s of p.scenes){const words=s.words?.length?s.words:s.narration.split(/\s+/).filter(Boolean).map((w,i,a)=>({w,start:i*s.duration/a.length,end:(i+1)*s.duration/a.length}));for(let i=0;i<words.length;i+=8){const group=words.slice(i,i+8);lines.push(`${format==='srt'?++n+'\n':''}${stamp(offset+group[0].start)} --> ${stamp(offset+Math.min(s.duration,group.at(-1).end))}\n${group.map(w=>w.w).join(' ')}\n`);}offset+=s.duration;}return (format==='vtt'?'WEBVTT\n\n':'')+lines.join('\n');}
