/* Real local speech, ASR, music mixing, incremental render and three delivery sizes. */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {defaultScene,validateProject} from '../kare/engine/render.js';
const base=`http://127.0.0.1:${process.env.STUDIO_PORT||8770}`,out=path.resolve(process.argv[2]||'output/pro-qa');fs.mkdirSync(out,{recursive:true});
async function api(route,body,raw=false){const r=await fetch(base+'/api/animation/'+route,body===undefined?{}:{method:'POST',headers:raw?{}:{'Content-Type':'application/json'},body:raw?body:JSON.stringify(body)});const v=await r.json();assert.ok(r.ok,v.error);return v;}
async function job(type,body){const {id}=await api('jobs',{type,...body}),start=Date.now();let n=0;while(true){const j=await api('jobs/'+id);if(n++%10===0)console.log(type,j.state,j.progress,j.message);assert.ok(!['error','cancelled'].includes(j.state),j.message);if(j.state==='done')return j.result;assert.ok(Date.now()-start<300000,'Job timeout');await new Promise(r=>setTimeout(r,1000));}}
function probe(file){return JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8',windowsHide:true}));}
const shape={id:'hero',name:'Nokta',entityId:'hero',type:'circle',x:.3,y:.4,width:.09,height:.09,color:'#c74f36',lineWidth:3,start:0,duration:.2,motion:'fade',text:'',points:[],keyframes:[{time:0,x:.3,ease:'linear'},{time:3,x:.65,ease:'smooth'}]};
const first={...defaultScene('line-art'),duration:4,composed:true,title:'Konuşmayla hareket',narration:'Bir nokta hareket ediyor.',objects:[shape,{...shape,id:'label',entityId:'',type:'text',x:.5,y:.2,width:.6,height:.05,color:'#392936',text:'Konuşmayla aynı anda.',keyframes:[]}]};
const second={...defaultScene('line-art'),duration:2,composed:true,title:'Devam eden nokta',carry:true,objects:[]};
let project=validateProject({version:1,name:'Kare · ses ve devamlılık denemesi',delivery:'1080',scenes:[first,second],voice:{provider:'windows',rate:1.1,pause:200,pitch:0}});
project=(await job('voice',{project,provider:'windows'})).project;assert.ok(project.scenes[0].audio.duration>0);
project=(await job('align',{project})).project;assert.equal(project.scenes[0].words.length,4);assert.match(project.scenes[0].alignment,/Whisper/);project.scenes[0].objects[0].cue={word:2,offset:0};
const tone=path.join(out,'pro-test-music.wav');execFileSync('ffmpeg',['-v','error','-y','-f','lavfi','-i','sine=frequency=165:duration=2','-af','volume=0.1',tone],{windowsHide:true});project.music={...await api('audio?name=music.wav',fs.readFileSync(tone),true),volume:.1,duck:.15};
const rendered=await job('render',{project,subtitles:true});assert.equal(rendered.cachedScenes,0);assert.ok(rendered.hasAudio&&rendered.audioUrl);const file=path.join(out,'pro-studio-sesli-ornek.mp4');fs.writeFileSync(file,Buffer.from(await (await fetch(base+rendered.url)).arrayBuffer()));let meta=probe(file);assert.equal(meta.streams.find(s=>s.codec_type==='video').width,1920);assert.ok(meta.streams.some(s=>s.codec_name==='aac'));assert.ok(Math.abs(+meta.format.duration-rendered.duration)<.1);
const mix=path.join(out,'pro-studio-ses-miksi.wav');fs.writeFileSync(mix,Buffer.from(await (await fetch(base+rendered.audioUrl)).arrayBuffer()));assert.equal(probe(mix).streams[0].codec_type,'audio');
const cached=await job('render',{project,subtitles:true});assert.equal(cached.cachedScenes,2);
project.scenes[1].background='#eee8de';const changed=await job('render',{project,subtitles:true});assert.equal(changed.cachedScenes,1);
const sizes=[];for(const [delivery,width,height] of [['vertical',1080,1920],['4k',3840,2160]]){const p=structuredClone(project);p.delivery=delivery;p.scenes=[{...second,carry:false,objects:[{...shape,keyframes:[],cue:null,x:.5}]}];p.music=null;const result=await job('render',{project:p,subtitles:false});const target=path.join(out,'pro-studio-'+delivery+'.mp4');fs.writeFileSync(target,Buffer.from(await (await fetch(base+result.url)).arrayBuffer()));meta=probe(target);assert.equal(meta.streams[0].width,width);assert.equal(meta.streams[0].height,height);sizes.push({delivery,width,height,duration:+meta.format.duration});}
fs.writeFileSync(path.join(out,'pro-studio-sesli-proje.json'),JSON.stringify(project,null,2));const packaged=await api('pro/package',{project});fs.writeFileSync(path.join(out,'pro-studio-sesli-proje.zip'),Buffer.from(await (await fetch(base+packaged.url)).arrayBuffer()));
const report={speechDuration:project.scenes[0].audio.duration,alignment:project.scenes[0].alignment,words:project.scenes[0].words,musicDucking:true,loudnessFilter:true,actual1080p:true,aacAudio:true,audioDownload:true,initialCache:rendered.cachedScenes,repeatCache:cached.cachedScenes,modifiedCache:changed.cachedScenes,delivery:sizes,mediaPackage:true,externalModelCalls:0};fs.writeFileSync(path.join(out,'pro-studio-integration-tests.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
