import puppeteer from 'puppeteer-core';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {closeRenderBrowser} from './close_render_browser.mjs';
const out=path.resolve(process.argv[2]||'output/pro-qa');fs.mkdirSync(out,{recursive:true});
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-gpu']});const errors=[];
try{
 const page=await browser.newPage();await page.setViewport({width:1440,height:1000});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${process.env.STUDIO_PORT||8770}/studio/#edit`,{waitUntil:'networkidle0'});await page.waitForFunction(()=>window.canvasStudio);
 const core=await page.evaluate(async()=>{
  const {validateProject,defaultScene,renderProject}=await import('/studio/engine/render.js'),{pose,carryScene,qualityCheck,subtitleFile}=await import('/studio/engine/pro.js');
  const obj={id:'one',type:'path',x:.5,y:.4,width:.2,height:.1,color:'#000000',lineWidth:3,start:0,duration:1,motion:'draw',text:'',points:[[.21,.31],[.5,.4],[.79,.31]],entityId:'hero',keyframes:[{time:0,x:.5,ease:'linear'},{time:4,x:.7,ease:'linear'}]};
  const a=defaultScene('line-art');a.objects=[obj];a.composed=true;a.duration=4;const b=defaultScene('line-art');b.objects=[];b.composed=true;b.carry=true;b.duration=4;
  const p=validateProject({version:1,scenes:[a,b]});const mid=pose(p.scenes[0].objects[0],2,p.scenes[0]).x,carry=carryScene(p,1).objects[0];
  const cv=document.createElement('canvas');cv.width=1280;cv.height=720;let hashes=[];
  for(const brush of ['solid','watercolor','pastel','ink','retro']){p.scenes[0].objects[0].brush=brush;renderProject(cv.getContext('2d'),2,p);hashes.push(cv.toDataURL());}
  p.scenes[0].words=[{w:'bir',start:.1,end:.6},{w:'iki',start:.7,end:1}];p.scenes[0].objects[0].cue={word:1,offset:.2};const cue=pose(p.scenes[0].objects[0],0,p.scenes[0]).start;
  p.assets=[{id:'asset',name:'Nesne',revision:1,objects:[{...p.scenes[0].objects[0],cue:null,keyframes:[]}]}];p.style.locked=true;p.style.palette=['#112233','#ddeeff'];const locked=validateProject(p);p.scenes[0].objects[0].cue={word:99,offset:0};
  return {mid,carryX:carry.x,carryPoint:carry.points[0][0],brushes:new Set(hashes).size,cue,style:locked.scenes[0].objects[0].color,assetStyle:locked.assets[0].objects[0].color,srt:subtitleFile(p),cueError:qualityCheck(p).some(i=>i.kind==='error')};
 });assert.equal(core.mid,.6);assert.equal(core.carryX,.7);assert.ok(Math.abs(core.carryPoint-.41)<.0001);assert.equal(core.brushes,5);assert.ok(Math.abs(core.cue-.9)<.0001);assert.equal(core.style,'#112233');assert.equal(core.assetStyle,'#112233');assert.match(core.srt,/00:00:00,100/);assert.ok(core.cueError);
 const click=async text=>{await page.evaluate(t=>{const b=[...document.querySelectorAll('#proContent button')].find(b=>b.textContent.startsWith(t));if(!b)throw Error('Button missing: '+t);b.click();},text);};
 const tool=async id=>{await page.click(`[data-tool="${id}"]`);};
 await page.click('#professionalOpen');await tool('layers');await click('＋ Dikdörtgen');await page.waitForSelector('#obj_name');await page.$eval('#obj_name',e=>{e.value='Hero';e.dispatchEvent(new Event('change'));});
 await page.$eval('#obj_entityId',e=>{e.value='hero';e.dispatchEvent(new Event('change'));});await click('Bu konumu anahtar kare yap');assert.equal(await page.evaluate(()=>canvasStudio.project.scenes[0].objects[0].keyframes.length),1);
 await tool('style');await click('Sahne nesnelerini kütüphaneye kaydet');assert.equal(await page.evaluate(()=>canvasStudio.project.assets.length),1);await click('Sahneye bağla');assert.ok(await page.evaluate(()=>canvasStudio.project.scenes[0].objects.some(o=>o.assetId)));
 await tool('math');await page.$eval('#mathExpr',e=>e.value='a*x^2');await click('Grafiği sahneye çiz');await page.waitForFunction(()=>canvasStudio.project.scenes[0].objects.some(o=>o.math?.plot));const before=await page.evaluate(()=>canvasStudio.project.scenes[0].objects.find(o=>o.math?.plot&&!o.math.axis&&!o.math.label).points);
 await page.$eval('#mathParam',e=>{e.value=2;e.dispatchEvent(new Event('change'));});await page.waitForFunction(()=>canvasStudio.project.scenes[0].objects.find(o=>o.math?.plot&&!o.math.axis&&!o.math.label).math.parameter===2);assert.notDeepEqual(await page.evaluate(()=>canvasStudio.project.scenes[0].objects.find(o=>o.math?.plot&&!o.math.axis&&!o.math.label).points),before);
 await click('Formülü sahneye ekle');await page.waitForFunction(()=>canvasStudio.project.scenes[0].objects.some(o=>o.svg),{timeout:30000});
 await tool('voice');await page.$eval('#voiceRate',e=>e.value=1.2);await page.$eval('#voiceLexicon',e=>e.value='{"GLM":"ci el em"}');await click('Anlatıcı ayarlarını kaydet');assert.equal(await page.evaluate(()=>canvasStudio.project.voice.rate),1.2);
 let patchBody;await page.setRequestInterception(true);page.on('request',req=>{if(req.url().endsWith('/api/animation/jobs')&&req.method()==='POST'&&JSON.parse(req.postData()).type==='patch'){patchBody=JSON.parse(req.postData());return req.respond({status:200,contentType:'application/json',body:JSON.stringify({id:'mock-pro-patch'})});}if(req.url().endsWith('/api/animation/jobs/mock-pro-patch')){const after=structuredClone(patchBody.project);after.scenes[0].objects.find(o=>o.id===patchBody.objectId).color='#27915f';return req.respond({status:200,contentType:'application/json',body:JSON.stringify({id:'mock-pro-patch',state:'done',progress:100,type:'patch',message:'Hazır',result:{project:after,originalProject:patchBody.project,sceneIndex:0,patch:{scope:'object',sceneId:patchBody.project.scenes[0].id,objectId:patchBody.objectId}}})});}req.continue();});
 await tool('patch');await page.$eval('#patchPrompt',e=>e.value='Nesneyi yeşil yap');const beforePatch=await page.evaluate(()=>canvasStudio.project);await click('Düzeltme taslağı hazırla');await page.waitForSelector('#proResult figure');assert.equal(await page.$$eval('#proResult figure',e=>e.length),2);assert.deepEqual(await page.evaluate(()=>canvasStudio.project),beforePatch);await page.evaluate(()=>canvasStudio.edit(q=>q.name='Üretim sırasında düzenlendi'));const beforeApply=await page.evaluate(()=>canvasStudio.project);await page.evaluate(()=>[...document.querySelectorAll('#proResult button')].find(b=>b.textContent.startsWith('Sonucu')).click());await page.waitForFunction(()=>canvasStudio.project.scenes[0].objects.some(o=>o.color==='#27915f'));assert.equal(await page.evaluate(()=>canvasStudio.project.name),beforeApply.name);await page.click('#undo');assert.deepEqual(await page.evaluate(()=>canvasStudio.project),beforeApply);
 await tool('board');assert.ok(await page.$('#boardDuration0'));await tool('quality');assert.ok(await page.$eval('#proContent',e=>e.textContent.includes('kontroller')));
 await tool('versions');await click('Sürüm kaydet');await page.waitForFunction(()=>document.querySelector('#versionList button'));await click('Projeyi medya dosyalarıyla paketle');await page.waitForSelector('#proResult a[href$="project.zip"]');await click('SRT / VTT altyazıları hazırla');await page.waitForSelector('#proResult a[href$="captions.srt"]');
 await tool('layers');await page.screenshot({path:path.join(out,'pro-studio-live.png'),fullPage:true});
 const project=await page.evaluate(()=>canvasStudio.project);fs.writeFileSync(path.join(out,'pro-studio-example.json'),JSON.stringify(project,null,2));
 const standalone=await page.evaluate(()=>canvasStudio.standaloneHtml(canvasStudio.project));const offline=await browser.newPage();offline.on('pageerror',e=>errors.push('offline '+e.message));await offline.setContent(standalone,{waitUntil:'load'});await offline.waitForFunction(()=>document.querySelector('canvas').getContext('2d').getImageData(640,360,1,1).data[3]);await page.bringToFront();
 await page.setViewport({width:390,height:844});await page.screenshot({path:path.join(out,'pro-studio-mobile.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false);assert.deepEqual(errors,[]);
 const report={engine:core,layerEdit:true,keyframes:true,linkedLibrary:true,parameterGraph:true,tex:true,voiceProfile:true,board:true,quality:true,targetedPatchPreview:true,patchApplyUndo:true,revisions:true,package:true,captions:true,offlineFormula:true,mobileOverflow:overflow,errors};fs.writeFileSync(path.join(out,'pro-studio-ui-tests.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){console.error({errors});throw error;}finally{await closeRenderBrowser(browser);}
